@host = http://localhost:9090

### test api
POST {{host}}/api
Content-Type: application/json

{
    "method": "foo.bar",
    "appkey": "abc",
    "timestamp": 123,
    "v":"1.0",
    "param":{"a":1,"foo":"bar"},
    "sign":"abc"
}


### test api
GET {{host}}/biz/foo/bar
Authorization: Basic admin:123123123


### test webhook
POST {{host}}/webhook/test/foo/foo.bar
Content-Type: application/json

{
    "sign":"abc"
}